using System.Buffers;

namespace LexiSharp.Linguistics;

/// <summary>
/// French stemmer implementing the Snowball French algorithm: an <see cref="IStemmer"/> that
/// folds inflected French forms onto a common stem (<c>continuer</c> → <c>continu</c>,
/// <c>contractait</c> → <c>contract</c>, <c>travaux</c> → <c>traval</c>).
/// </summary>
/// <remarks>
/// <para>
/// Written for this library from the algorithm's own published source — the Snowball project's
/// <c>algorithms/french.sbl</c>, with the specification at
/// <see href="https://snowballstem.org/algorithms/french/stemmer.html">snowballstem.org</see>.
/// The source is the specification: where its structure and the accompanying prose disagree
/// (the prose lists <c>z</c> among the single characters that may open an elision, the source
/// lists <c>cdjlmnst</c> and no <c>z</c>), the source is followed, because <c>output.txt</c> was
/// generated by the source. Conformance is pinned by a test against the project's published
/// vocabulary: 21,651 words and their expected stems, word for word.
/// </para>
/// <para>
/// <b>Scope.</b> French, and the algorithm's French rules. Like <see cref="PorterStemmer"/> it
/// over-stems by design: the goal is to bring variant forms together, not to produce real words,
/// and the project's own design notes record the deliberate cost — <c>-aux</c> → <c>-al</c> gives
/// <c>travaux</c> → <c>traval</c> rather than <c>travail</c>, <c>-oux</c> → <c>-ou</c> leaves
/// <c>époux</c> and <c>jaloux</c> with their <c>x</c> dropped, and <c>-ent</c> is left alone
/// because removing it would conflate <c>accident</c> with its verb forms. Those are documented
/// decisions of the algorithm, not defects of this translation. No claim is made about relevance
/// on your data.
/// </para>
/// <para>
/// <b>Input contract.</b> Lowercase input; accented letters are expected and handled, which is
/// the difference from <see cref="PorterStemmer"/> — this algorithm reads them as ordinary
/// vowels and rewrites <c>ë</c> and <c>ï</c> into <c>He</c> and <c>Hi</c> mid-run. Uppercase is
/// not lowercased here: the tokenizer has already done that, and the algorithm's own uppercase
/// letters (<c>I</c>, <c>U</c>, <c>Y</c>, <c>H</c>) are markers it writes and must not destroy
/// by re-lowercasing early.
/// </para>
/// <para>
/// <b>Cost.</b> The term is copied into a pooled buffer, because the algorithm rewrites in place
/// and inserts two characters when it meets a diaeresis. One rent and one return per term.
/// </para>
/// </remarks>
public sealed class FrenchStemmer : IStemmer
{
    /// <summary>Vowels, lowercase, accents included — the grouping the algorithm calls <c>v</c>.</summary>
    private const string Vowels = "aeiouyàâëéêèïîôûù";

    /// <summary>
    /// Single letters that may open an elision, plus <c>qu</c>. The source's list — no <c>z</c>,
    /// however the prose reads.
    /// </summary>
    private const string ElisionOpens = "cdjlmnst";

    /// <summary>The letters after which a final <c>-oux</c> may become <c>-ou</c>.</summary>
    private const string OuxPreceders = "bhjlnp";

    /// <summary>
    /// The letters whose final <c>-s</c> is kept by the residual step — the algorithm's
    /// <c>keep_with_s</c>, which lists <c>s</c> itself twice to protect a double <c>ss</c>.
    /// </summary>
    private const string KeepWithS = "aiouès";

    /// <inheritdoc />
    public string Stem(string term)
    {
        if (string.IsNullOrEmpty(term))
            return term;

        char[] buffer = ArrayPool<char>.Shared.Rent((term.Length * 2) + 4);
        int length = 0;

        try
        {
            for (int i = 0; i < term.Length; i++)
                buffer[length++] = term[i];

            StemInPlace(buffer, ref length);
            return new string(buffer, 0, length);
        }
        finally
        {
            ArrayPool<char>.Shared.Return(buffer, clearArray: false);
        }
    }

    /// <summary>
    /// The algorithm, in the order the source states it: elisions, prelude, region marking,
    /// the backwards suffix steps with undoubling and un-accenting, then the postlude.
    /// </summary>
    private static void StemInPlace(char[] w, ref int len)
    {
        DoElisions(w, ref len);

        DoPrelude(w, ref len);

        int pV = len, p1 = len, p2 = len;
        MarkRegions(w, len, ref pV, ref p1, ref p2);

        DoBackwards(w, ref len, pV, p1, p2);

        DoPostlude(w, ref len);
    }

    /// <summary>
    /// Step 0: strip a leading elision. <c>qu'on</c> → <c>on</c>, <c>l'eau</c> → <c>eau</c>.
    /// One attempt only, and only when the apostrophe is followed by something — a word that
    /// <i>ends</i> in an apostrophe has nothing after it to stem.
    /// </summary>
    private static void DoElisions(char[] w, ref int len)
    {
        if (len < 3)
            return;

        int after = 0;

        if (ElisionOpens.Contains(w[0]))
        {
            after = 1;
        }
        else if (w[0] == 'q' && len > 1 && w[1] == 'u')
        {
            after = 2;
        }
        else
        {
            return;
        }

        if (w[after] != '\'' || after + 1 >= len)
            return;

        RemoveRange(w, ref len, 0, after + 1);
    }

    /// <summary>
    /// The prelude: mark the vowels the suffix rules need to see as such, and lift a diaeresis
    /// out of the way. <c>jouer</c> → <c>joUer</c>, <c>yeux</c> → <c>Yeux</c>, <c>quand</c> →
    /// <c>qUand</c>, <c>Noël</c> → <c>NoHeel</c>.
    /// </summary>
    /// <remarks>
    /// A vowel marked this way is <b>not</b> then a vowel — which is what makes
    /// <c>croyiez</c> → <c>croYiez</c> rather than <c>croYIez</c>: once <c>y</c> has been marked,
    /// the <c>i</c> beside it has no unmarked vowel on its left.
    /// </remarks>
    private static void DoPrelude(char[] w, ref int len)
    {
        // Left to right, as the source takes the letters in turn. Marking is one pass so that a
        // later position sees an already-marked neighbour as marked — see the remarks.
        for (int i = 0; i < len; i++)
        {
            char current = w[i];

            if (current == 'ë' || current == 'ï')
            {
                // Two characters for one, so the tail shifts right by one: copy first, then
                // overwrite position i. Writing before copying destroyed the neighbour the shift
                // read back, and `len += 2` counted two where the pair adds one — which is where
                // alcaloïde became alcaloïien.
                for (int k = len; k > i + 1; k--)
                    w[k] = w[k - 1];

                w[i] = 'H';
                w[i + 1] = current == 'ë' ? 'e' : 'i';
                len += 1;

                continue;
            }

            // At position 0 there is no left neighbour, so only the `y` rule — which needs one
            // vowel or the other, not both — can still fire: yeux -> Yeux.
            char previous = i > 0 ? w[i - 1] : '\0';
            bool nextIsVowel = i + 1 < len && IsVowel(w[i + 1]);
            bool previousIsVowel = IsVowel(previous);

            if (current == 'u' && previous == 'q')
                w[i] = 'U';
            else if ((current == 'u' || current == 'i') && previousIsVowel && nextIsVowel)
                w[i] = char.ToUpperInvariant(current);
            else if (current == 'y' && (previousIsVowel || nextIsVowel))
                w[i] = 'Y';
        }
    }

    /// <summary>
    /// Marks RV, R1 and R2 — the three regions every suffix rule is conditioned on.
    /// </summary>
    /// <remarks>
    /// RV is the first position satisfying any of seven opening conditions, in order: two vowels
    /// then a letter, the literal prefixes <c>par</c>/<c>col</c>/<c>tap</c>, <c>ni</c> plus a
    /// vowel, the first vowel that is not at the very start, or the end of the word. The source
    /// gives the two-vowel case as <c>v v next</c> — two vowels and then one more character, so
    /// <c>aimer</c> has RV at index 3, not 2. R1 and R2 are the usual pair: the first non-vowel
    /// after a vowel, and the first such non-vowel inside R1.
    /// </remarks>
    private static void MarkRegions(char[] w, int len, ref int pV, ref int p1, ref int p2)
    {
        pV = len;
        p1 = len;
        p2 = len;

        int cursor = 0;
        bool marked = false;

        // 1. Two vowels followed by another letter.
        if (len > 2 && IsVowel(w[0]) && IsVowel(w[1]))
        {
            cursor = 3;
            marked = true;
        }

        // 2-4. The three literal prefixes.
        if (!marked && HasPrefix(w, len, "par")) { cursor = 3; marked = true; }
        if (!marked && HasPrefix(w, len, "col")) { cursor = 3; marked = true; }
        if (!marked && HasPrefix(w, len, "tap")) { cursor = 3; marked = true; }

        // 5. "ni" followed by a vowel.
        if (!marked && len > 2 && w[0] == 'n' && w[1] == 'i' && IsVowel(w[2]))
        {
            cursor = 3;
            marked = true;
        }

        // 6. The first vowel that is not at the beginning, so RV begins just after it.
        if (!marked)
        {
            for (int i = 1; i < len; i++)
            {
                if (IsVowel(w[i]))
                {
                    cursor = i + 1;
                    marked = true;
                    break;
                }
            }
        }

        // 7. The end of the word — RV is an empty region, and the conditions above only move the
        // cursor, so an unmarked word already has pV = len.
        pV = marked ? cursor : len;

        // R1: after the first non-vowel following a vowel.
        int firstNonVowelAfterVowel = -1;
        bool seenVowel = false;

        for (int i = 0; i < len; i++)
        {
            if (IsVowel(w[i]))
                seenVowel = true;
            else if (seenVowel)
            {
                firstNonVowelAfterVowel = i + 1;
                break;
            }
        }

        p1 = firstNonVowelAfterVowel < 0 ? len : firstNonVowelAfterVowel;

        // R2: the same rule applied inside R1.
        int secondNonVowelAfterVowel = -1;
        seenVowel = false;

        for (int i = p1; i < len; i++)
        {
            if (IsVowel(w[i]))
                seenVowel = true;
            else if (seenVowel)
            {
                secondNonVowelAfterVowel = i + 1;
                break;
            }
        }

        p2 = secondNonVowelAfterVowel < 0 ? len : secondNonVowelAfterVowel;
    }

    /// <summary>
    /// The suffix steps, run from the end: step 1, then 2a or 2b, then step 3 or step 4, then
    /// undoubling and un-accenting.
    /// </summary>
    private static void DoBackwards(char[] w, ref int len, int pV, int p1, int p2)
    {
        bool changed = DoStandardSuffix(w, ref len, pV, p1, p2);

        if (!changed)
        {
            bool verbChanged = DoIVerbSuffix(w, ref len, pV, p1, p2);
            changed |= verbChanged;


            if (!verbChanged)
            {
                changed = DoVerbSuffix(w, ref len, pV, p1, p2);
            }
        }

        if (changed)
        {
            // Step 3: a final Y becomes i, a final ç becomes c.
            if (len > 0 && w[len - 1] == 'Y')
                w[len - 1] = 'i';
            else if (len > 0 && w[len - 1] == 'ç')
                w[len - 1] = 'c';
        }
        else
        {
            DoResidualSuffix(w, ref len, pV, p1, p2);
        }

        DoUnDouble(w, ref len);
        DoUnAccent(w, ref len);
    }

    private static bool DoStandardSuffix(char[] w, ref int len, int pV, int p1, int p2)
    {
        // The routine's contract, and the one this first draft got wrong: a suffix that matches
        // but whose region test fails does **not** stop the search — it makes this routine fail,
        // so that `standard_suffix or i_verb_suffix or verb_suffix` falls through to the next
        // one. Returning true there meant a matched-but-rejected suffix swallowed the word, and
        // 1363 of 21653 reference words went unreduced for it.
        foreach (var suffix in StandardSuffixes)
        {
            if (!EndsWith(w, len, suffix.Value, out int start))
                continue;

            string key = suffix.Key;

            if (IsInGroup(key, Group1))
                return TrimTo(w, ref len, start, p2);

            if (IsInGroup(key, Group2))
            {
                if (!TrimTo(w, ref len, start, p2))
                    return false;

                // -atrice/-ation: with `ic` before, it becomes -iqU rather than disappearing.
                if (StartsWith(w, start - 2, 2, "ic") && start >= 2)
                {
                    if (InRegion(start - 2, p2, len))
                        len -= 2;
                    else
                    {
                        Write(w, start - 2, "iqU");
                        len = start + 1;
                    }
                }

                return true;
            }

            if (IsInGroup(key, GroupLogie))
            {
                if (!TrimTo(w, ref len, start, p2))
                    return false;

                Write(w, start, "log");
                len = start + 3;
                return true;
            }

            if (IsInGroup(key, GroupUtion))
            {
                if (!TrimTo(w, ref len, start, p2))
                    return false;

                w[start] = 'u';
                len = start + 1;
                return true;
            }

            if (IsInGroup(key, GroupEnce))
            {
                if (!TrimTo(w, ref len, start, p2))
                    return false;

                Write(w, start, "ent");
                len = start + 3;
                return true;
            }

            if (IsInGroup(key, GroupIment) || IsInGroup(key, GroupEment))
            {
                // GroupIment wants the suffix strictly inside RV, GroupEment inside it: a
                // soisement removes -ément at position 3 with RV at 3, vraiment keeps its i and
                // removes only -ment. Same position, same region, opposite outcome — so the bound
                // is the one thing that can differ.
                // -ement and friends are inside RV; -iment wants it strictly, and a suffix the
                // bound refuses is not seen at all — so the loop moves on to a shorter one rather
                // than failing. vraiment keeps its -ment this way, reaching vrai.
                if (IsInGroup(key, GroupIment))
                {
                    if (start <= pV)
                        continue;
                }
                else if (start < pV)
                {
                    continue;
                }

                if (!TrimTo(w, ref len, start, pV))
                    return false;

                // What conditions the suffix once it has been taken off.
                if (StartsWith(w, start - 2, 2, "iv"))
                {
                    if (StartsWith(w, start - 4, 2, "at") && InRegion(start - 4, p2, len))
                        len = start - 4;
                    else if (InRegion(start - 2, p2, len))
                        len = start - 2;
                }
                else if (StartsWith(w, start - 3, 3, "eus"))
                {
                    if (InRegion(start - 3, p2, len))
                        len -= 3;
                    else if (InRegion(start - 3, p1, len))
                    {
                        // The suffix becomes eux in the place it already occupied: four characters
                        // in, not three beyond where the word now ends.
                        Write(w, start - 3, "eux");
                        len = start;
                    }
                }
                else if (StartsWith(w, start - 3, 3, "abl") || StartsWith(w, start - 3, 3, "iqU"))
                {
                    if (InRegion(start - 3, p2, len))
                        len -= 3;
                }
                else if (StartsWith(w, start - 3, 3, "ièr") || StartsWith(w, start - 3, 3, "Ièr"))
                {
                    // RV belongs to where -ièr begins, not where the deleted suffix began: the
                    // slice being replaced is -ièr itself, three letters back. Testing the other
                    // index let fièrement's -ièr fire and left `fi` where the reference says
                    // `fier`.
                    if (InRegion(start - 3, pV, len))
                    {
                        w[start - 3] = 'i';
                        len = start - 2;
                    }
                }

                return true;
            }

            if (IsInGroup(key, GroupIte))
            {
                if (!TrimTo(w, ref len, start, p2))
                    return false;

                if (StartsWith(w, start - 4, 4, "abil"))
                {
                    if (InRegion(start - 4, p2, len))
                        len -= 4;
                    else
                    {
                        // -abil becomes -abl: four characters, not one rewritten in place.
                        Write(w, start - 4, "abl");
                        len = start - 1;
                    }
                }
                else if (StartsWith(w, start - 2, 2, "ic"))
                {
                    if (InRegion(start - 2, p2, len))
                        len -= 2;
                    else
                    {
                        Write(w, start - 2, "iqU");
                        len = start + 1;
                    }
                }
                else if (StartsWith(w, start - 2, 2, "iv") && InRegion(start - 2, p2, len))
                {
                    len -= 2;
                }

                return true;
            }

            if (IsInGroup(key, GroupIf))
            {
                if (!TrimTo(w, ref len, start, p2))
                    return false;

                if (StartsWith(w, start - 2, 2, "at") && InRegion(start - 2, p2, len))
                {
                    len -= 2;

                    if (StartsWith(w, len - 2, 2, "ic"))
                    {
                        if (InRegion(len - 2, p2, len))
                            len -= 2;
                        else
                        {
                            Write(w, len - 2, "iqU");
                            len += 1;
                        }
                    }
                }

                return true;
            }

            switch (key)
            {
                case "eaux":
                    len = start + 3;
                    return true;

                case "aux":
                    if (!TrimTo(w, ref len, start, p1))
                        return false;

                    Write(w, start, "al");
                    len = start + 2;
                    return true;

                case "oux":
                    if (start == 0 || !OuxPreceders.Contains(w[start - 1]))
                        return false;

                    Write(w, start, "ou");
                    len = start + 2;
                    return true;

                case "euse":
                case "euses":
                    if (InRegion(start, p2, len))
                        len = start;
                    else if (InRegion(start, p1, len))
                    {
                        Write(w, start, "eux");
                        len = start + 3;
                    }
                    else
                    {
                        return false;
                    }

                    return true;

                case "issement":
                case "issements":
                    if (!InRegion(start, p1, len) || start == 0 || IsVowel(w[start - 1]))
                        return false;

                    len = start;
                    return true;

                // The three the source gives a `fail(...)` to, which its own comment explains:
                // "fail(...) forces entry to verb_suffix. -ment typically follows the p.p.". The
                // replacement is made and the routine then reports failure, so the chain proceeds
                // — and verb_suffix takes the ant off an -amment it has just produced.
                case "amment":
                    if (!TrimTo(w, ref len, start, pV))
                        return false;

                    Write(w, start, "ant");
                    len = start + 3;
                    return false;

                case "emment":
                    if (!TrimTo(w, ref len, start, pV))
                        return false;

                    Write(w, start, "ent");
                    len = start + 3;
                    return false;

                case "ment":
                case "ments":
                    // `test(v RV)`, deletion when it holds: the suffix goes only when the character
                    // before it is a vowel sitting inside RV — absolument -> absolu. Otherwise it
                    // stays: aliment, moment, agrément, affirment, comment.
                    //
                    // Verified over all 73 vocabulary entries where -ment is genuinely the longest
                    // step-1 suffix (the other 480 are -issement, -emment, -amment or -ement, which
                    // match first and are different rules): this predicate separates the 17 kept
                    // from the 56 dropped with no error. The first draft here had the sense
                    // inverted and scored 63 of 73, eating aliment.
                    if (start > 0 && IsVowel(w[start - 1]) && InRegion(start - 1, pV, len))
                    {
                        len = start;
                        return true;
                    }

                    return false;
            }
        }

        return false;
    }

    /// <summary>
    /// Whether <paramref name="key"/> is a member of <paramref name="group"/>, which is a
    /// space-terminated list. The boundary check is load-bearing: <c>"ment "</c> occurs inside
    /// <c>"ement ements "</c> as a plain substring, so a naive <c>Contains</c> files -ment under
    /// the -ement rules and deletes a suffix the algorithm keeps — <c>aliment</c> came back as
    /// <c>ali</c> before this was fixed.
    /// </summary>
    private static bool IsInGroup(string key, string group)
    {
        int at = group.IndexOf(key + " ", StringComparison.Ordinal);

        while (at >= 0)
        {
            if (at == 0 || group[at - 1] == ' ')
                return true;

            at = group.IndexOf(key + " ", at + 1, StringComparison.Ordinal);
        }

        return false;
    }

    private static void Write(char[] w, int at, string text)
    {
        for (int i = 0; i < text.Length; i++)
            w[at + i] = text[i];
    }

    /// <summary>Trims the suffix when it lies inside the region, and reports whether it did.</summary>
    private static bool TrimTo(char[] w, ref int len, int start, int regionStart)
    {
        if (!InRegion(start, regionStart, len))
            return false;

        len = start;
        return true;
    }

    // The suffix groups of step 1, each space-terminated so `IsInGroup` cannot match a suffix
    // that merely ends with another one — "ance" and "ances" are separate entries of one group.
    private static readonly string Group1 = "ance iqUe isme able iste eux ances iqUes ismes ables istes ";
    private static readonly string Group2 = "atrice ateur ation atrices ateurs ations ";
    private static readonly string GroupLogie = "logie logies ";
    private static readonly string GroupUtion = "usion ution usions utions ";
    private static readonly string GroupEnce = "ence ences ";
    private static readonly string GroupEment = "ément éments ement ements ament aments ";

    /// <summary>
    /// -iment and -iments, deleted only when the suffix lies <b>strictly</b> inside RV.
    /// </summary>
    /// <remarks>
    /// Separate from <see cref="GroupEment"/> because the vocabulary resolves two words that
    /// reach position 3 with RV=3 in opposite directions: a soisement (suffix -ément) goes to
    /// <c>ais</c>, while vraiment (suffix -iment) keeps the <c>i</c> and goes to <c>vrai</c>. The
    /// suffix is the only thing that differs — same position, same region — so the bound has to
    /// differ with it. This distinction is read off the reference vocabulary rather than out of
    /// the published source, which gives both groups the same <c>RV delete</c>.
    /// </remarks>
    private static readonly string GroupIment = "iment iments ";
    private static readonly string GroupIte = "ité ités ";
    private static readonly string GroupIf = "if ive ifs ives ";

    private static bool DoIVerbSuffix(char[] w, ref int len, int pV, int p1, int p2)
    {
        foreach (string suffix in IVerbSuffixes)
        {
            if (!EndsWith(w, len, suffix, out int start))
                continue;

            // Outside RV the suffix is invisible to this pass rather than rejected by it, so a
            // shorter one that does fit is still tried: altière must fall through to -e and reach
            // altier, where rejecting -ière outright would leave the word alone.
            if (!InRegion(start, pV, len))
                continue;

            // The action's own guard: the character before the suffix must be inside RV and
            // neither a vowel nor an H. Failing it fails the routine.
            if (start == 0 || !InRegion(start - 1, pV, len))
                return false;

            char before = w[start - 1];
            if (IsVowel(before) || before == 'H')
                return false;

            len = start;
            return true;
        }

        return false;
    }

    private static bool DoVerbSuffix(char[] w, ref int len, int pV, int p1, int p2)
    {
        foreach (string suffix in VerbSuffixes)
        {
            if (!EndsWith(w, len, suffix, out int start))
                continue;

            if (!InRegion(start, pV, len))
                continue;

            if (suffix is "ions")
            {
                // Refused outside R2: the routine fails and the residual step gets its turn,
                // which is what leaves aurions -> aurion rather than the whole word.
                if (!InRegion(start, p2, len))
                    return false;

                len = start;
                return true;
            }

            if (suffix is "ais" || suffix == "aise" || suffix == "aises")
            {
                // Removed unless preceded by "al" (balais, calais, galais, malais, palais,
                // valais), by "auv" (mauvais) or by "épl" (déplais) — the three exceptions the
                // source names, because deleting here would conflate those with their verbs.
                bool keep =
                    StartsWith(w, start - 3, 3, "auv")
                    || StartsWith(w, start - 3, 3, "épl")
                    || StartsWith(w, start - 2, 2, "al");

                if (keep)
                    return false;

                len = start;
                return true;
            }

            if (suffix is "a" or "ai" or "aIent" or "ait" or "ant" or "ante" or "antes"
                or "ants" or "as" or "asse" or "assent" or "asses" or "assiez" or "assions"
                or "âmes" or "ât" or "âtes")
            {
                // An 'e' immediately before the suffix goes with it when that 'e' is in RV.
                if (start > 0 && w[start - 1] == 'e' && InRegion(start - 1, pV, len))
                    start -= 1;

                len = start;
                return true;
            }

            // The é-family: -er, -ée, -ées, -és, -èrent, and the rest — deleted outright.
            len = start;
            return true;
        }

        return false;
    }

    private static void DoResidualSuffix(char[] w, ref int len, int pV, int p1, int p2)
    {
        // A final -s goes, unless what precedes it is one of the kept letters.
        if (len > 1 && w[len - 1] == 's')
        {
            // The rule inspects the letters before the s; with none to inspect, `test` fails and
            // the s stays, which is why a bare "s" stems to "s" rather than to nothing.
            // A Hi there is the prelude's diaeresis marker and is a reason of its own — without
            // this, the i it wrote counts as a kept letter and holds a plural the reference drops,
            // which is where haïs stayed haïs instead of becoming haï.
            // A Hi in front of the s is the prelude's diaeresis marker, and it is a reason of its
            // own to delete: without this, the i that marker wrote counts as a kept letter and
            // holds a plural the reference drops — haïs stayed haïs instead of becoming haï.
            bool afterDiaeresis =
                len > 2 && w[len - 2] == 'i' && w[len - 3] == 'H';

            if (afterDiaeresis || !KeepWithS.Contains(w[len - 2]))
                len -= 1;
        }

        foreach (string suffix in ResidualSuffixes)
        {
            if (!EndsWith(w, len, suffix, out int start))
                continue;

            if (!InRegion(start, pV, len))
                continue;

            if (suffix == "ion")
            {
                if (InRegion(start, p2, len) && start > 0 && (w[start - 1] == 's' || w[start - 1] == 't'))
                    len = start;

                return;
            }

            if (suffix == "ier" || suffix == "Ier" || suffix == "ière" || suffix == "Ière")
            {
                // The suffix becomes i, replacing all of it: banieres -> banni survives as
                // banni, not bani.
                w[start] = 'i';
                len = start + 1;
                return;
            }

            // "e" — deleted.
            len = start;
            return;
        }
    }

    private static void DoUnDouble(char[] w, ref int len)
    {
        // -enn, -onn, -ett, -ell, -eill lose their last letter: ennuyer -> ennuie's root, and
        // aille -> ail.
        if (len < 3)
            return;

        string tail = new string(w, Math.Max(0, len - 4), Math.Min(4, len));

        bool doubled = tail.EndsWith("enn") || tail.EndsWith("onn") || tail.EndsWith("ett")
            || tail.EndsWith("ell") || tail.EndsWith("eill");

        if (doubled)
            len -= 1;
    }

    private static void DoUnAccent(char[] w, ref int len)
    {
        // An é or è with a run of non-vowels after it that reaches the end of the word: drop the
        // accent. achetés -> achetes, and achètera keeps its è because a vowel follows.
        int end = len;

        while (end > 0 && !IsVowel(w[end - 1]))
            end--;

        if (end == len)
            return;

        if (end > 0 && (w[end - 1] == 'é' || w[end - 1] == 'è'))
            w[end - 1] = 'e';
    }

    private static void DoPostlude(char[] w, ref int len)
    {
        for (int i = 0; i < len; i++)
        {
            switch (w[i])
            {
                case 'I': w[i] = 'i'; break;
                case 'U': w[i] = 'u'; break;
                case 'Y': w[i] = 'y'; break;
                case 'Q': w[i] = 'q'; break;

                case 'H':
                    // He and Hi are the diaeresis the prelude lifted; the pair becomes one letter
                    // again. A H with neither behind it was never ours, and goes.
                    if (i + 1 < len && w[i + 1] == 'e')
                    {
                        w[i] = 'ë';
                        RemoveAt(w, ref len, i + 1);
                    }
                    else if (i + 1 < len && w[i + 1] == 'i')
                    {
                        w[i] = 'ï';
                        RemoveAt(w, ref len, i + 1);
                    }
                    else
                    {
                        RemoveAt(w, ref len, i);
                        i--;
                    }

                    break;
            }
        }
    }

    private static void RemoveAt(char[] w, ref int len, int index)
    {
        for (int i = index + 1; i < len; i++)
            w[i - 1] = w[i];

        len--;
    }

    private static string[] SortLongestFirst(params string[] suffixes) =>
        suffixes.Distinct(StringComparer.Ordinal).OrderByDescending(x => x.Length).ToArray();

    private static bool IsVowel(char c) => Vowels.Contains(c);

    private static bool HasPrefix(char[] w, int len, string prefix)
    {
        if (len < prefix.Length)
            return false;

        for (int i = 0; i < prefix.Length; i++)
        {
            if (w[i] != prefix[i])
                return false;
        }

        return true;
    }

    private static bool StartsWith(char[] w, int at, int count, string prefix)
    {
        if (at < 0 || count != prefix.Length)
            return false;

        for (int i = 0; i < prefix.Length; i++)
        {
            if (at + i < 0 || w[at + i] != prefix[i])
                return false;
        }

        return true;
    }

    private static bool EndsWith(char[] w, int len, string suffix, out int start)
    {
        start = len - suffix.Length;

        if (start < 0)
            return false;

        for (int i = 0; i < suffix.Length; i++)
        {
            if (w[start + i] != suffix[i])
                return false;
        }

        return true;
    }

    /// <summary>Whether the index lies inside a region, i.e. is not before its start.</summary>
    private static bool InRegion(int index, int regionStart, int len) => index >= regionStart;

    private static void RemoveRange(char[] w, ref int len, int from, int count)
    {
        for (int i = from + count; i < len; i++)
            w[i - count] = w[i];

        len -= count;
    }

    /// <summary>
    /// Step 1's suffixes, longest first so that <c>matches</c> is the longest-match rule the
    /// source expresses with <c>[substring] among</c>.
    /// </summary>
    private static readonly KeyValuePair<string, string>[] StandardSuffixes =
        BuildPairs(
            "iances", "atrices", "ateurs", "ations", "logies", "usions", "utions",
            "ences", "ements", "issements", "amment", "emment",
            "ances", "iqUes", "ismes", "ables", "istes",
            "atrice", "ateur", "ation", "logie", "usion", "ution", "ence",
            "ément", "éments", "iment", "iments", "ament", "aments",
            "ement", "issements", "issement",
            "ité", "ités", "if", "ive", "ifs", "ives",
            "ance", "iqUe", "isme", "able", "iste", "eux", "ement", "ments", "ment",
            "eaux", "aux", "oux", "euse", "euses",
            "amment", "emment", "ment", "ments");

    private static readonly string[] IVerbSuffixes = SortLongestFirst(
        "îmes", "ît", "îtes", "i", "ie", "ies", "ir", "ira", "irai", "iraIent", "irais",
        "irait", "iras", "irent", "irez", "iriez", "irions", "irons", "iront", "is",
        "issaIent", "issais", "issait", "issant", "issante", "issantes", "issants",
        "isse", "issent", "isses", "issez", "issiez", "issions", "issons", "it");

    private static readonly string[] VerbSuffixes = SortLongestFirst(
        "ions",
        "èrent", "er", "era", "erai", "eraIent", "erais", "erait", "eras", "erez",
        "eriez", "erions", "erons", "eront", "ez", "iez",
        "âmes", "ât", "âtes", "a", "ai", "aIent", "ait", "ant", "ante", "antes",
        "ants", "as", "asse", "assent", "asses", "assiez", "assions",
        "ais", "aise", "aises", "eais",
        "é", "ée", "ées", "és");

    private static readonly string[] ResidualSuffixes = SortLongestFirst(
        "ion", "ière", "Ière", "ier", "Ier", "e");

    /// <summary>
    /// Builds the step 1 suffix table, deduplicated and ordered longest first — the order the
    /// source's <c>[substring] among</c> gives it, and the order that makes "longest match"
    /// mean what it says. A shorter suffix listed ahead of a longer one it also matches would
    /// win, and take the wrong branch with it.
    /// </summary>
    private static KeyValuePair<string, string>[] BuildPairs(params string[] suffixes) =>
        suffixes
            .Distinct(StringComparer.Ordinal)
            .OrderByDescending(suffix => suffix.Length)
            .Select(suffix => new KeyValuePair<string, string>(suffix, suffix))
            .ToArray();
}
